services:
  # Основная база данных PostgreSQL
  db:
    image: postgres:18-alpine
    container_name: simple-coffeeshop-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB_DEV},${POSTGRES_DB_TEST}
      TZ: UTC
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
      # Скрипт для создания нескольких баз данных при инициализации
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  adminer:
    image: adminer
    container_name: simple-coffeeshop-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
