services:
  # База данных (Скрыта от внешнего мира)
  db-prod:
    image: postgres:18-alpine
    container_name: sc-db-prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_PROD:-simple_coffeeshop_prod}
    volumes:
      - sc-prod-data:/var/lib/postgresql/data
    networks:
      - sc-prod-network

  # API Сервер (Внутренний)
  api:
    build:
      context: .
      dockerfile: Dockerfile
      # Использует стандартный stage 'runner' из Dockerfile
      args:
        PKG_NAME: "@simple-coffeeshop/api"
    container_name: sc-api-prod
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL_PROD}
      NODE_ENV: production
    depends_on:
      - db-prod
    networks:
      - sc-prod-network

  # Nginx + Фронтенд (Публичный)
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner-web # Явно указываем этап с Nginx
      args:
        PKG_NAME: "@simple-coffeeshop/web"
    container_name: sc-web-prod
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api
    networks:
      - sc-prod-network

networks:
  sc-prod-network:

volumes:
  sc-prod-data:
