services:
  db:
    image: postgres:18-alpine
    container_name: sc-dev-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      # Переменная ниже требует наличия init-db.sh для работы
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB},${POSTGRES_DB_TEST}
      TZ: UTC
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - sc-network

  adminer:
    image: adminer
    container_name: sc-adminer-dev
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sc-network

  redis-prod:
    image: redis:8-alpine
    container_name: sc-redis-prod
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - sc-redis-data:/data
    networks:
      - sc-network

# Обязательное объявление сети
networks:
  sc-network:
    driver: bridge

# Объявление томов
volumes:
  sc-prod-data:
  sc-redis-data:
  postgres_data:
    name: simple-coffeeshop-postgres-data
