services:
  db-dev:
    image: postgres:18-alpine
    container_name: sc-db-dev
    ports:
      - "5432:5432" # Открыто наружу для тебя
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB_DEV:-simple_coffeeshop_dev}
    volumes:
      - sc-dev-data:/var/lib/postgresql/data
    networks:
      - sc-dev-network

  adminer:
    image: adminer
    container_name: sc-adminer
    ports:
      - "8080:8080"
    networks:
      - sc-dev-network

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile # Или отдельный Dockerfile.dev
    volumes:
      - .:/app # [КРИТИЧНО]: Синхронизация кода
      - /app/node_modules # Чтобы не затереть модули внутри контейнера
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "5173:5173" # Порт для Vite
    networks:
      - sc-dev-network

networks:
  sc-dev-network:

volumes:
  sc-dev-data:
